version: "3.9"

services:
  nginx:
    build: .
    container_name: reptor-nginx
    ports:
      - "80:80"
    depends_on:
      - test
      - beta
      - version2
      - dev
      - staging
      - prod
      - www
      - qa
    restart: unless-stopped

  test:
    image: nginx:alpine
    container_name: test
    volumes:
      - ./html/test:/usr/share/nginx/html:ro

  beta:
    image: nginx:alpine
    container_name: beta
    volumes:
      - ./html/beta:/usr/share/nginx/html:ro

  version2:
    image: nginx:alpine
    container_name: version2
    volumes:
     - ./html/version2:/usr/share/nginx/html:ro

  dev:
    image: nginx:alpine
    container_name: dev
    volumes:
      - ./html/dev:/usr/share/nginx/html:ro

  staging:
    image: nginx:alpine
    container_name: staging
    volumes:
      - ./html/staging:/usr/share/nginx/html:ro

  prod:
   image: nginx:alpine
   container_name: prod
   volumes:
     - ./html/prod:/usr/share/nginx/html:ro

  www:
   image: nginx:alpine
   container_name: www
   volumes:
    - ./html/www:/usr/share/nginx/html:ro

  qa:
    image: nginx:alpine
    container_name: qa
    volumes:
      - ./html/qa:/usr/share/nginx/html:ro
