worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        least_conn;
        server test.mydomain.com;
        server beta.mydomain.com;
        server version2.mydomain.com;
        server dev.mydomain.com;
        server staging.mydomain.com;
        server prod.mydomain.com;
        server www.mydomain.com;
        server qa.mydomain.com;
    }

    server {
        listen 80;

        server_name mydomain.com;

        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
