worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    upstream backend {
        least_conn;
        server test.mydomain.test;
        server beta.mydomain.test;
        server version2.mydomain.test;
        server dev.mydomain.test;
        server staging.mydomain.test;
        server prod.mydomain.test;
        server www.mydomain.test;
        server qa.mydomain.test;
    }

    server {
        listen 80;
        server_name mydomain.test;

        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;
        }
    }
}
